version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-management-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xe
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - oracle-db

  oracle-db:
    shm_size: 8g
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: xe
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
    driver: local
